### ISSUE TITLE
Status is not showing in Original Theme

### ISSUE THREAD

**Issue by eduardocazangi-picpay** [medeirosinacio/jira-backlog-issue-status-extension#1]
Status is not showing in Original Theme

**Comment by medeirosinacio** [comment]
Thank you for reporting the error. 

The issue has been fixed in the new release v0.3.2, which you can find [here](https://github.com/medeirosinacio/jira-backlog-issue-status-extension/releases/tag/v0.3.2) and https://github.com/medeirosinacio/jira-backlog-issue-status-extension/compare/v0.3.1...v0.3.2.
